using System.Collections.Generic;

namespace YuCap;

/// <summary>
/// Minimal UI localization: Japanese strings are the keys (and the fallback),
/// English is looked up from the table. Switching language rebuilds nothing —
/// it takes effect on the next launch, which keeps every call site trivial.
/// </summary>
internal static class L
{
    public static bool English;

    public static string T(string ja) =>
        English && Map.TryGetValue(ja, out string? en) ? en : ja;

    public static string F(string jaFormat, params object?[] args) =>
        string.Format(T(jaFormat), args);

    private static readonly Dictionary<string, string> Map = new()
    {
        // ---- Menus ----
        ["ファイル(&F)"] = "&File",
        ["スナップショットを保存"] = "Save snapshot",
        ["スナップショットをコピー"] = "Copy snapshot",
        ["保存先フォルダを開く"] = "Open snapshot folder",
        ["スナップショット設定..."] = "Snapshot settings...",
        ["連写スナップショット..."] = "Burst snapshots...",
        ["Windows起動時に自動実行"] = "Run at Windows startup",
        ["グローバルホットキーを有効化"] = "Enable global hotkeys",
        ["ホットキー設定..."] = "Hotkey settings...",
        ["カーソルを自動的に隠す"] = "Auto-hide mouse cursor",
        ["隠すまでの時間"] = "Hide after",
        ["{0}秒"] = "{0} sec",
        ["カーソル自動非表示: {0}秒"] = "Cursor auto-hide: {0}s",
        ["カーソル自動非表示: オフ"] = "Cursor auto-hide: off",
        ["ホットキー設定"] = "Hotkey settings",
        ["スナップショット:"] = "Snapshot:",
        ["ミュート:"] = "Mute:",
        ["PiP切替:"] = "Toggle PiP:",
        ["欄をクリックしてキーを押してください。Esc で無効化できます。"] =
            "Click a field and press a key combo. Esc disables it.",
        ["終了"] = "Exit",
        ["デバイス(&D)"] = "&Device",
        ["映像デバイス"] = "Video device",
        ["音声デバイス"] = "Audio device",
        ["（開くと更新）"] = "(refreshes on open)",
        ["映像モード (解像度/FPS)"] = "Video mode (resolution/FPS)",
        ["音声バッファ設定..."] = "Audio buffer settings...",
        ["入力レベルを最大にする"] = "Maximize input level",
        ["このデバイスは入力レベルを変更できません"] = "This device has no input level control",
        ["入力レベルは既に最大です"] = "Input level is already at maximum",
        ["入力レベル {0}% → 100%"] = "Input level {0}% → 100%",
        ["優先デバイス設定..."] = "Preferred device...",
        ["ミュート"] = "Mute",
        ["表示(&V)"] = "&View",
        ["アスペクト比 / 表示モード"] = "Aspect ratio / display mode",
        ["アスペクト比を保持"] = "Keep aspect ratio",
        ["ウィンドウに引き伸ばし"] = "Stretch to window",
        ["原寸表示"] = "Actual size (1:1)",
        ["整数倍表示 (くっきり)"] = "Integer scaling (sharp)",
        ["ウィンドウ比率を映像に固定"] = "Lock window ratio to video",
        ["回転 / 反転"] = "Rotation / flip",
        ["回転なし"] = "No rotation",
        ["{0}° 回転"] = "Rotate {0}°",
        ["左右反転"] = "Flip horizontally",
        ["ズームをリセット"] = "Reset zoom",
        ["ウィンドウサイズ"] = "Window size",
        ["全画面表示"] = "Fullscreen",
        ["一時停止 / 再開"] = "Pause / resume",
        ["ピクチャインピクチャ"] = "Picture-in-picture",
        ["PiP設定"] = "PiP settings",
        ["不透明度 {0}%"] = "Opacity {0}%",
        ["不透明度（通常時）"] = "Opacity (idle)",
        ["不透明度（マウスオーバー時）"] = "Opacity (hover)",
        ["サイズ（映像原寸比）"] = "Size (% of source)",
        ["表示位置"] = "Position",
        ["右下"] = "Bottom-right",
        ["左下"] = "Bottom-left",
        ["右上"] = "Top-right",
        ["左上"] = "Top-left",
        ["クリックスルー"] = "Click-through",
        ["オプション(&O)"] = "&Options",
        ["ウィンドウ枠を非表示"] = "Hide window frame",
        ["常に前面に表示"] = "Always on top",
        ["メニューバーを隠す"] = "Hide menu bar",
        ["ステータスバーを表示"] = "Show status bar",
        ["ヘルプ(&H)"] = "&Help",
        ["言語 / Language"] = "言語 / Language",
        ["バージョン情報..."] = "About...",
        ["更新を確認..."] = "Check for updates...",
        ["起動時に更新を確認"] = "Check for updates at startup",
        ["起動時の更新確認: オン"] = "Startup update check: on",
        ["起動時の更新確認: オフ"] = "Startup update check: off",
        ["現在のバージョンは {0} です。\n更新はありません。"] =
            "You are running {0}.\nNo updates available.",
        ["新しいバージョン {0} があります（現在 {1}）。\n\n今すぐ更新しますか？\n更新後、YuCap は自動的に再起動します。"] =
            "Version {0} is available (you have {1}).\n\nUpdate now?\nYuCap will restart automatically.",
        ["インストール先に書き込めないため、自動更新できません。\nリリースページを開きますか？"] =
            "Cannot write to the install folder, so the update cannot be applied.\nOpen the releases page instead?",
        ["更新をダウンロード中"] = "Downloading update",
        ["{0} をダウンロードしています..."] = "Downloading {0}...",
        ["更新のダウンロードに失敗しました。\n\n{0}"] = "Failed to download the update.\n\n{0}",
        ["更新の適用に失敗しました。元の状態に戻しました。\n\n{0}"] =
            "Failed to apply the update; the previous version was restored.\n\n{0}",
        // ---- Context menu ----
        ["全画面切替"] = "Toggle fullscreen",
        ["スナップショット保存"] = "Save snapshot",
        ["ウィンドウ枠なし表示"] = "Borderless",
        ["メニューバー表示"] = "Show menu bar",
        ["ステータスバー表示"] = "Show status bar",
        // ---- Device lists ----
        ["（デバイスなし）"] = "(no devices)",
        ["自動 (最大解像度)"] = "Auto (max resolution)",
        ["（利用可能なモードなし）"] = "(no modes available)",
        // ---- OSD ----
        ["音量 {0}%"] = "Volume {0}%",
        ["ミュート解除 ({0}%)"] = "Unmuted ({0}%)",
        ["音声がありません"] = "No audio",
        ["映像がありません"] = "No video",
        ["映像なし"] = "No video",
        ["ズーム {0}%"] = "Zoom {0}%",
        ["一時停止"] = "Paused",
        ["再開"] = "Resumed",
        ["保存しました: {0}"] = "Saved: {0}",
        ["保存に失敗しました"] = "Save failed",
        ["クリップボードにコピーしました"] = "Copied to clipboard",
        ["コピーに失敗しました"] = "Copy failed",
        ["連写 {0}/{1}"] = "Burst {0}/{1}",
        ["連写を停止しました"] = "Burst stopped",
        ["連写を開始します ({0}枚 / {1}秒間隔)"] = "Burst started ({0} shots / every {1}s)",
        ["解像度が未確定です"] = "Resolution not ready",
        ["映像デバイスが切断されました"] = "Video device disconnected",
        ["映像を再接続しました: {0}"] = "Video reconnected: {0}",
        ["音声を再接続しました: {0}"] = "Audio reconnected: {0}",
        ["回転 {0}°"] = "Rotated {0}°",
        ["この環境では回転に対応していません"] = "Rotation not supported here",
        ["この環境では反転に対応していません"] = "Flip not supported here",
        ["左右反転: オン"] = "Flip: on",
        ["左右反転: オフ"] = "Flip: off",
        ["常に前面: オン"] = "Always on top: on",
        ["常に前面: オフ"] = "Always on top: off",
        ["音声バッファ {0}ms"] = "Audio buffer {0}ms",
        ["スナップショット: {0}"] = "Snapshots: {0}",
        ["映像: {0}"] = "Video: {0}",
        ["音声: {0}"] = "Audio: {0}",
        ["映像モード: 自動"] = "Video mode: auto",
        ["PiP: オン"] = "PiP: on",
        ["PiP: オフ"] = "PiP: off",
        ["クリックスルー: オン (Ctrl+Alt+Pで解除)"] = "Click-through: on (Ctrl+Alt+P to exit)",
        ["クリックスルー: オフ"] = "Click-through: off",
        ["ホットキーの登録に失敗しました"] = "Failed to register global hotkeys",
        ["ホットキー使用中のため無効: {0}"] = "Hotkey taken by another app: {0}",
        // ---- Status bar ----
        ["映像"] = "Video",
        ["音声"] = "Audio",
        ["音量"] = "Volume",
        ["なし"] = "none",
        ["遅延"] = "delay",
        // ---- Dialogs ----
        ["音声バッファ設定"] = "Audio buffer settings",
        ["バッファ長 (ms):"] = "Buffer (ms):",
        ["値を大きくすると遅延は増えますが音切れに強くなります。\n（既定: 200ms）"] =
            "Larger values add delay but resist dropouts.\n(default: 200ms)",
        ["プリセット:"] = "Presets:",
        ["低遅延 60"] = "Low 60",
        ["標準 120"] = "Normal 120",
        ["安定 250"] = "Stable 250",
        ["この値が実際の音声遅延の目安になります。\n小さいほど低遅延ですが、音切れが出たら上げてください。\n実測値はステータスバーの「遅延」に表示されます。"] =
            "This value is the audio delay the app now holds.\nLower is snappier; raise it if you hear dropouts.\nThe measured value is shown in the status bar.",
        ["キャンセル"] = "Cancel",
        ["スナップショット設定"] = "Snapshot settings",
        ["保存先:"] = "Folder:",
        ["参照..."] = "Browse...",
        ["形式:"] = "Format:",
        ["PNG (無劣化)"] = "PNG (lossless)",
        ["JPEG (高画質)"] = "JPEG (high quality)",
        ["既定に戻す"] = "Reset to default",
        ["スナップショットの保存先フォルダ"] = "Snapshot destination folder",
        ["連写スナップショット"] = "Burst snapshots",
        ["間隔 (秒):"] = "Interval (s):",
        ["枚数:"] = "Count:",
        ["開始"] = "Start",
        ["優先デバイス設定"] = "Preferred device",
        ["キーワード:"] = "Keyword:",
        ["デバイス名にこの語を含む機器を起動時に自動選択します。\n（既定: JVA14）"] =
            "Devices whose name contains this word are\nauto-selected at startup. (default: JVA14)",
        ["バージョン情報"] = "About",
        ["バージョン {0}"] = "Version {0}",
        ["使用ライブラリ:"] = "Libraries:",
        ["言語を切り替えました。次回起動時に反映されます。"] =
            "Language changed. It takes effect on the next launch.",
        // ---- Message boxes ----
        ["映像入力デバイスが見つかりません。\nキャプチャデバイスの接続を確認して「再試行」を押してください。\n（キャンセルしても、後から接続すれば自動で再接続します）"] =
            "No video input device found.\nCheck the capture device connection and press Retry.\n(Even if you cancel, it reconnects automatically when plugged in.)",
        ["音声入力デバイスが見つかりません。\n接続を確認して「再試行」を押してください。\n（キャンセルしても、後から接続すれば自動で再接続します）"] =
            "No audio input device found.\nCheck the connection and press Retry.\n(Even if you cancel, it reconnects automatically when plugged in.)",
        ["映像デバイスの初期化に失敗しました。\n\n{0}"] = "Failed to initialize the video device.\n\n{0}",
        ["音声デバイスの初期化に失敗しました。\n\n{0}"] = "Failed to initialize the audio device.\n\n{0}",
        ["映像デバイスの切り替えに失敗しました。\n\n{0}"] = "Failed to switch video device.\n\n{0}",
        ["音声デバイスの切り替えに失敗しました。\n\n{0}"] = "Failed to switch audio device.\n\n{0}",
        ["映像モードの変更に失敗しました。\n\n{0}"] = "Failed to change video mode.\n\n{0}",
        ["音声の再初期化に失敗しました。\n\n{0}"] = "Failed to reinitialize audio.\n\n{0}",
    };
}
